[package]
name = "mistralrs-core"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
candle-core.workspace = true
candle-nn.workspace = true
serde.workspace = true
serde_json.workspace = true
candle-transformers = { git = "https://github.com/EricLBuehler/candle.git", version = "0.5.0" }
candle-flash-attn = { git = "https://github.com/EricLBuehler/candle.git", version = "0.5.0", optional = true }
dirs = "5.0.1"
hf-hub = "0.3.2"
thiserror = "1.0.57"
tokenizers = { version = "0.15.2", default-features = false, features = ["progressbar", "onig"] }
tqdm = "0.7.0"
range-checked = { git = "https://github.com/EricLBuehler/range-checked.git", version = "0.1.0" }
chrono = "0.4.34"
mistralrs-lora = { version = "0.1.0", path = "../mistralrs-lora" }
minijinja = "1.0.12"
either.workspace = true
indexmap.workspace = true
half = "2.4.0"
accelerate-src = { workspace = true, optional = true }
intel-mkl-src = { workspace = true, optional = true }
tracing.workspace = true
rand = "0.8.5"
regex-automata = "0.4.6"
rustc-hash = "1.1.0"
vob = "3.0.3"
cfgrammar = "0.13.3"
lrtable = "0.13.3"
galil-seiferas = "0.1.5"
clap.workspace = true

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda", "candle-transformers/cuda"]
cudnn = ["candle-core/cudnn"]
metal = ["candle-core/metal", "candle-nn/metal", "candle-transformers/metal"]
flash-attn = ["cuda", "candle-transformers/flash-attn", "dep:candle-flash-attn"]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
mkl = ["candle-core/mkl", "candle-nn/mkl", "candle-transformers/mkl"]

